- hosts: localhost
  user: super_user
  become: yes
  roles:
    - role: packages
      vars:
        package_name: PHP
        packages:
            - composer
            - php-bcmath
            - php-common
            - php-curl
            - php-dom
            - php-gd
            - php-json
            - php-mbstring
            - php-mongodb
            - php-mysql
            - php-pgsql
            - php-xml
            - php-zip
            - phpunit