- hosts: localhost
  user: super_user
  become: yes
  roles:
    - role: packages
      vars:
        package_name: dependency for ppa
        packages:
            - software-properties-common
    - role: repo-apt-add-ppa
      vars:
        repo: ppa:ondrej/php
    - role: packages
      vars:
        package_name: PHP8
        packages:
            - php8.0
            - composer
            - php8.0-bcmath
            - php8.0-common
            - php8.0-curl
            - php8.0-dom
            - php8.0-gd
            # - php8.0-json
            - php8.0-mbstring
            - php8.0-mongodb
            - php8.0-mysql
            - php8.0-pgsql
            - php8.0-xml
            - php8.0-zip
            - phpunit