- name: Java
  import_playbook: develop-lang-java.yml
- hosts: localhost
  user: super_user
  become: yes
  vars_files:
    - [ "vars.yml" ]
  ignore_errors: yes
  roles:
    - role: snap-android
    - role: user-to-group
      vars:
        group: plugdev
        user: "{{sudo_user}}"
    - role: packages
      vars:
        package_name: adb
        packages:
            - adb