- hosts: localhost
  user: super_user
  become: yes
  vars_files:
    - [ "vars.yml" ]
  ignore_errors: yes
  roles:
    - role: packages
      when: ansible_facts['os_family'] == 'Debian'
      vars:
        package_name: APT
        packages:
            - software-properties-common
            - apt-transport-https
    - role: repo-add
      vars:
        repo_name: vscode
        repo_key_url: https://packages.microsoft.com/keys/microsoft.asc
        repo: https://packages.microsoft.com/repos/vscode
    - role: packages
      vars:
        package_name: develop-vscode
        packages:
            - code
    - role: gantsign.visual-studio-code-extensions
      users:
        - username: "{{sudo_user}}"
          visual_studio_code_extensions:
            # generic
            - mikestead.dotenv
            # erd
            - kaishuu0123.vscode-erd-preview
            - mikkel-ol.er-syntax-highlighting
            # laravel
            - onecentlin.laravel-blade
            - onecentlin.laravel5-snippets
            - austenc.laravel-blade-spacer
            - ryannaddy.laravel-artisan
            - amiralizadeh9480.laravel-extra-intellisense
            - stef-k.laravel-goto-controller
            - codingyu.laravel-goto-view
            # docker
            - ms-azuretools.vscode-docker
            - ms-vscode-remote.remote-containers
            - ms-kubernetes-tools.vscode-kubernetes-tools
            - googlecloudtools.cloudcode
            - mindaro.mindaro