- hosts: localhost
  user: super_user
  become: yes
  vars_files:
    - [ "vars.yml" ]
  ignore_errors: yes
  roles:
    - role: download-install
      vars:
        package: mysql-workbench-community_8.0.26-1ubuntu21.04_amd64
        url: https://dev.mysql.com/get/Downloads/MySQLGUITools/
