- hosts: localhost
  user: super_user
  become: yes
  vars_files:
    - [ "vars.yml" ]
  ignore_errors: yes
  roles:
    - role: packages
      when: ansible_facts['os_family'] == 'Debian'
      vars:
        package_name: APT
        packages:
            - software-properties-common
            - apt-transport-https
    - role: repo-add
      vars:
        repo_name: edge
        repo_key_url: https://packages.microsoft.com/keys/microsoft.asc
        repo: https://packages.microsoft.com/repos/edge
    - role: packages
      vars:
        package_name: Microsoft Edge
        packages:
            - microsoft-edge-dev