- hosts: localhost
  user: super_user
  become: yes
  vars_files:
    - [ "vars.yml" ]
  ignore_errors: yes
  roles:
    - role: packages
      vars:
        package_name: vpn connect client
        packages:
            - openvpn
            - network-manager-openvpn
            - network-manager-openvpn-gnome
            - network-manager-vpnc
