- name: Fetch Telegram package
  get_url:
    url: https://telegram.org/dl/desktop/linux
    dest: /tmp/tsetup.2.8.10.tar.xz
    mode: '0777'
# - name: Extract Telegram package
#   ansible.buildin.unarchive:
#     src: /tmp/tsetup.2.8.10.tar.xz
#     dest: "{{ super_user }}/Desktop/"