- name: Fetch Telegram package
  get_url:
    url: https://telegram.org/dl/desktop/linux
    dest: "/tmp/{{ archive_name }}"
    mode: '0777'
- name: Extract Telegram package
  unarchive:
    src: "/tmp/{{ archive_name }}"
    dest: "/home/{{ super_user }}/Desktop/"